markdown: rdiscount
permalink: /:title/
url: http://baren.github.io
name: 巴人
author: 巴人
qq: 
email: barenaq@gmail.com
duoshuo: 
beian: 
cnzz: 
weibo: 
github: baren
pygments: true
safe: true
paginate: 20
about: "个人技术笔记"
